### ISSUE TITLE
A Cloud Storage bucket name is missing on CI environments

### ISSUE THREAD

**Issue by jimmyandrade** [multei/api#15]
**Given** I am running CI on Travis
**When** Travis runs `jest`
**Then** console shows the following:

```shell
> @multei/api@0.1.0 test /home/travis/build/multei/api
> jest
 PASS  src/middlewares/handleServerErrors.unit.test.js
 PASS  src/knex/index.unit.test.js
 FAIL  src/middlewares/addHeaders.api.test.js
  ● Test suite failed to run
    A bucket name is needed to use Cloud Storage.
```

```js
      26 | const storage = new Storage()
      27 | 
    > 28 | const bucket = storage.bucket(CLOUD_BUCKET)
         |                        ^
      29 | 
      30 | function getPublicUrl(filename) {
      31 |   debug(`Getting public URL for ${filename}`)
```
```
      at Storage.bucket (node_modules/@google-cloud/storage/build/src/storage.js:138:19)
      at Object.<anonymous> (src/lib/googleCloudStorage.js:28:24)
      at Object.<anonymous> (src/api/v1/parkings/crud.js:7:35)
 FAIL  src/api/index.api.test.js
  ● Test suite failed to run
    A bucket name is needed to use Cloud Storage.
```

```js
      26 | const storage = new Storage()
      27 | 
    > 28 | const bucket = storage.bucket(CLOUD_BUCKET)
         |                        ^
      29 | 
      30 | function getPublicUrl(filename) {
      31 |    debug(`Getting public URL for ${filename}`)
```
```
      at Storage.bucket (node_modules/@google-cloud/storage/build/src/storage.js:138:19)
      at Object.<anonymous> (src/lib/googleCloudStorage.js:28:24)
      at Object.<anonymous> (src/api/v1/parkings/crud.js:7:35)
 PASS  ./knexfile.test.js
 FAIL  src/middlewares/handleNotFound.api.test.js
  ● Test suite failed to run
    A bucket name is needed to use Cloud Storage.
```

```js
      26 | const storage = new Storage()
      27 | 
    > 28 | const bucket = storage.bucket(CLOUD_BUCKET)
         |                        ^
      29 | 
      30 | function getPublicUrl(filename) {
      31 |    debug(`Getting public URL for ${filename}`)
```

```
      at Storage.bucket (node_modules/@google-cloud/storage/build/src/storage.js:138:19)
      at Object.<anonymous> (src/lib/googleCloudStorage.js:28:24)
      at Object.<anonymous> (src/api/v1/parkings/crud.js:7:35)
File               | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
-------------------|---------|----------|---------|---------|-------------------
All files          |     100 |      100 |     100 |     100 |                   
 api               |     100 |      100 |     100 |     100 |                   
  knexfile.js      |     100 |      100 |     100 |     100 |                   
 api/src/knex      |     100 |      100 |     100 |     100 |                   
  index.js         |     100 |      100 |     100 |     100 |                   
 ...rc/middlewares |     100 |      100 |     100 |     100 |                   
  ...rverErrors.js |     100 |      100 |     100 |     100 |                   
-------------------|---------|----------|---------|---------|-------------------
Test Suites: 3 failed, 3 passed, 6 total
Tests:       11 passed, 11 total
Snapshots:   0 total
Time:        2.567s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
The command "npm test" exited with 1.
cache.2
store build cache
Done. Your build exited with 1.
```

**To Reproduce**
1. Go to https://travis-ci.org/multei/api
2. Click on **Job log**
3. Scroll down to line 218

**Expected behavior**
Tests should not fail

**Screenshots**
![image](https://user-images.githubusercontent.com/2307245/75092872-191df500-555b-11ea-8b26-946120c2ad2d.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Node version: 13.9.0
 - NPM version: 6.13.7
- NVM version: 0.35.2

**Comment by jimmyandrade** [comment]
Closed by https://github.com/multei/api/commit/8a6ba63c6bc91f470552f95bc4e793f631d65a66
