### ISSUE TITLE
🐛 [Bug] TypeError: ExpressMiddleware is not a function

### ISSUE THREAD

**Issue by jimmyandrade** [multei/api#48]
### English

Until version `1.x.x` of the `express-api-problem` library, there was no error. When we started using version `2.x.x`, these errors were observed.

### Portuguese (Brasil)

Até a versão `1.x.x` da biblioteca express-api-problem, não havia erro. Quando passamos a utilizar a versão `2.x.x`, esses erros foram observados.

## Steps to reproduce the behavior:

1. Navigate to project root;
2. Run `npm start` on your Terminal. Application will start on port 3000;
3. See error:

```shell
/usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js run start --scripts-prepend-node-path=auto

> @multei/api@0.1.0 start
> node ./bin/www

/src/app.js:35
app.use(ExpressMiddleware())
        ^

TypeError: ExpressMiddleware is not a function
    at Object.<anonymous> (/src/app.js:35:9)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Module.require (internal/modules/cjs/loader.js:1043:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/bin/www:6:13)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @multei/api@0.1.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @multei/api@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

Process finished with exit code 1
```

## Expected behavior

**Given** I am on the project root directory
**When** I run `npm start` **and** open http://localhost:3000/v1/parkings
**Then** I got some response

## Screenshots

![image](https://user-images.githubusercontent.com/2307245/78589503-a9b44a00-7816-11ea-9041-cc85ee658a17.png)

## Desktop
 - OS: macOS 
 - Version: 10.15.3 (19D76)

### debug

- [debug](https://www.npmjs.com/package/debug)

### express-api-problem

- [express-api-problem docs](https://github.com/kamranahmedse/express-api-problem#express-api-problem)
- [express-api-problem on GitHub](https://github.com/kamranahmedse/express-api-problem)
- [express-api-problem on npm](https://www.npmjs.com/package/express-api-problem)

## CheckList do kickoff

- [x] A análise da história está concluída?
- [x] QA (ou pessoa que assumiu o papel de QA) revisou a análise?
- [x] A história está completa com todos os detalhes e as informações relevantes?
  (Ex.: Contexto, Escopo, Fora de Escopo, Critérios de aceite, etc);
- [x] O valor de negócio da história está bem entendido? (se aplicável)
- [x] Esta história não tem dependência de outras histórias futuras?
- [x] Não existem dívidas técnicas (débitos técnicos) relacionadas a história;
- [x] Há protótipos de telas para essa história (se aplicável)
- [x] Há detalhes na história de mensagens de erro e outros feedbacks para o usuário (se aplicável)
- [x] Há mensagens de ajuda ou outros textos definidos na história (se aplicável)
- [x] A história está em um tamanho adequado
- [x] Existe feature toggle para a feature (se aplicável)

## Checklist do deskcheck

- [x] Há testes unitários que validem a implementação? (se aplicável)
- [x] A história foi executada manualmente
- [x] A história não trouxe regressões ou impacto negativo a outras implementações
- [x] Todos os critérios de aceite foram cobertos
- [x] A história não precisa de feedback ou correção
- [x] Foi testada uma jornada completa do usuário através da história (se aplicável)
- [ ] As alterações de código passaram em todas as pipelines

**Comment by jimmyandrade** [comment]
@tuliooassis comecei a adicionar algumas informações na _issue_, mas no refinamento de mais tarde vamos finalizar isso :)

**Comment by jimmyandrade** [comment]
@all-contributors please add @tuliooassis for code

**Comment by jimmyandrade** [comment]
@all-contributors please add @jimmyandrade for bug, projectManagement and review
